- name: ensures backup dirs exists
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - "{{ pg_backup_dir }}"
    - "{{ pg_archive_logs_dir }}"
    - "{{ pg_full_backup_dir }}"
    - "{{ scripts_dir }}"

- name: Template configuration file for pgsql_backup.sh
  template:
    src:  pgsql_backup.sh.j2
    dest: '{{ scripts_dir }}/pgsql_backup.sh'
    mode: '0755'

- name: Creates a cron file for full db backup in /etc/cron.d
  cron:
    name: pgsql_backup
    minute: "{{ pgsql_backup_min }}"
    hour: "{{ pgsql_backup_hour }}"
    user: root
    job: "{{ scripts_dir }}/pgsql_backup.sh"
    cron_file: pgsql_backup

- name: Template configuration file for clean_wal_archive.sh
  template:
    src:  clean_wal_archive.sh.j2
    dest: '{{ scripts_dir }}/clean_wal_archive.sh'
    mode: '0755'

- name: Creates a cron file for clean wal archive in /etc/cron.d
  cron:
    name: clean_wal_archive
    minute: "*/30"
    hour: "*"
    user: root
    job: "{{ scripts_dir }}/clean_wal_archive.sh"
    cron_file: clean_wal_archive
