- name: restart pgsql 
  systemd:
    state: restarted
    daemon_reload: yes
    name: postgresql-{{ ver }}
  
- name: restart zabbix-proxy
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: zabbix-proxy
